Getting around to some random stuff

diff --git a/.github/workflows/cross.yml b/.github/workflows/cross.yml
--- a/.github/workflows/cross.yml
+++ b/.github/workflows/cross.yml
@@ -6,9 +6,10 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - env:
+          AUTHOR_TESTING: 0
           AUTOMATED_TESTING: 1
         name: 'Test on ${{ inputs.os }}'
-        uses: cross-platform-actions/action@v0.22.0
+        uses: cross-platform-actions/action@v0.23.0
         with:
           architecture: '${{ inputs.arch }}'
           cpu_count: 4
@@ -27,10 +28,27 @@ jobs:
             curl -L https://cpanmin.us | sudo /usr/local/bin/perl${{inputs.perl}}${{ inputs.os == 'freebsd' && '.2' || ''}} - --notest App::cpanminus Module::Build::Tiny
             sudo cpanm --installdeps --notest .
             sudo /usr/local/bin/perl${{inputs.perl}}${{ inputs.os == 'freebsd' && '.2' || ''}} Build.PL
-            ./Build build --verbose
             ./Build test --verbose
+            command1_exit_code=$?
+            # Check if the first command exited successfully (exit code 0)
+            if [ $command1_exit_code -eq 0 ]; then
+              # Run the second command
+              sudo /usr/local/bin/perl${{inputs.perl}}${{ inputs.os == 'freebsd' && '.2' || ''}} -V > test-output-${{ inputs.arch }}-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
+              command2_exit_code=$?
+            else
+              # Print error message to a file (replace "error.log" with your desired filename)
+              echo "Error!" > test-output-${{ inputs.arch }}-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt
+              # Exit with the first command's exit code
+              exit $command1_exit_code
+            fi
           shell: bash
           version: '${{ inputs.version }}'
+      - name: Upload results as artifact
+        uses: actions/upload-artifact@v4.0.0
+        with:
+          if-no-files-found: error
+          name: 'test-output-${{ inputs.arch }}-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}'
+          path: 'test-output-${{ inputs.arch }}-${{ inputs.os }}-${{ inputs.perl }}${{ inputs.flags }}.txt'
 name: bsd module
 on:
   workflow_call:
